
name: Merge

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  DEV_AMI_ID: ${{secrets.DEV_AMI_ID}}
  DEMO_AMI_NAME: ${{secrets.DEMO_AMI_NAME}}
  
on:
  push:
    branches: [ main ]

jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.3

    - name: Download Packer plugin libraries
      run: packer init custom-ami.pkr.hcl

    - name: Building Packer Template
      run: packer build custom-ami.pkr.hcl
